import yaml from 'js-yaml';
import { sortJsonKeys } from './diffService';

// Format / Beautify JSON
export function formatJson(
  rawJson: string,
  options: { indent?: 2 | 4 | 'tab'; sortKeys?: boolean } = {}
): { formatted: string; error?: string } {
  try {
    const parsed = JSON.parse(rawJson);
    const obj = options.sortKeys ? sortJsonKeys(parsed) : parsed;
    const space = options.indent === 'tab' ? '\t' : options.indent || 2;
    return { formatted: JSON.stringify(obj, null, space) };
  } catch (err: any) {
    return { formatted: rawJson, error: err.message };
  }
}

// Minify JSON
export function minifyJson(rawJson: string): { minified: string; error?: string } {
  try {
    const parsed = JSON.parse(rawJson);
    return { minified: JSON.stringify(parsed) };
  } catch (err: any) {
    return { minified: rawJson, error: err.message };
  }
}

// Auto-repair common JSON syntax flaws (single quotes, trailing commas, unquoted keys)
export function autoRepairJson(rawJson: string): { repaired: string; error?: string } {
  try {
    // 1. Replace single quotes with double quotes
    let clean = rawJson.replace(/'/g, '"');
    // 2. Remove trailing commas in objects or arrays
    clean = clean.replace(/,(\s*[}\]])/g, '$1');
    // 3. Quote unquoted keys: e.g. { foo: "bar" } -> { "foo": "bar" }
    clean = clean.replace(/([{,]\s*)([a-zA-Z0-9_$]+)\s*:/g, '$1"$2":');

    const parsed = JSON.parse(clean);
    return { repaired: JSON.stringify(parsed, null, 2) };
  } catch (err: any) {
    return { repaired: rawJson, error: `Could not auto-repair JSON: ${err.message}` };
  }
}

// JSON to YAML
export function jsonToYaml(rawJson: string): { yamlText: string; error?: string } {
  try {
    const parsed = JSON.parse(rawJson);
    return { yamlText: yaml.dump(parsed) };
  } catch (err: any) {
    return { yamlText: '', error: `JSON to YAML Error: ${err.message}` };
  }
}

// YAML to JSON
export function yamlToJson(rawYaml: string): { jsonText: string; error?: string } {
  try {
    const parsed = yaml.load(rawYaml);
    return { jsonText: JSON.stringify(parsed, null, 2) };
  } catch (err: any) {
    return { jsonText: '', error: `YAML to JSON Error: ${err.message}` };
  }
}

// JSON to TypeScript Interfaces
export function jsonToTypeScript(rawJson: string, rootInterfaceName: string = 'RootObject'): {
  tsCode: string;
  error?: string;
} {
  try {
    const parsed = JSON.parse(rawJson);
    const interfaces: string[] = [];

    function capitalize(str: string) {
      return str.charAt(0).toUpperCase() + str.slice(1);
    }

    function getType(val: any, keyName: string): string {
      if (val === null) return 'any';
      if (typeof val === 'string') return 'string';
      if (typeof val === 'number') return 'number';
      if (typeof val === 'boolean') return 'boolean';

      if (Array.isArray(val)) {
        if (val.length === 0) return 'any[]';
        const itemType = getType(val[0], `${keyName}Item`);
        return `${itemType}[]`;
      }

      if (typeof val === 'object') {
        const subName = capitalize(keyName);
        generateInterface(val, subName);
        return subName;
      }

      return 'any';
    }

    function generateInterface(obj: Record<string, any>, name: string) {
      const lines = [`export interface ${name} {`];
      for (const [key, value] of Object.entries(obj)) {
        const safeKey = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key) ? key : `"${key}"`;
        const typeStr = getType(value, key);
        lines.push(`  ${safeKey}: ${typeStr};`);
      }
      lines.push('}');
      interfaces.push(lines.join('\n'));
    }

    if (Array.isArray(parsed)) {
      if (parsed.length > 0 && typeof parsed[0] === 'object') {
        generateInterface(parsed[0], rootInterfaceName);
      }
      interfaces.push(`export type ${rootInterfaceName}List = ${rootInterfaceName}[];`);
    } else if (typeof parsed === 'object' && parsed !== null) {
      generateInterface(parsed, rootInterfaceName);
    } else {
      return { tsCode: `export type ${rootInterfaceName} = ${typeof parsed};` };
    }

    return { tsCode: interfaces.join('\n\n') };
  } catch (err: any) {
    return { tsCode: '', error: `TypeScript Generator Error: ${err.message}` };
  }
}

// JSON to Go Structs
export function jsonToGo(rawJson: string, rootStructName: string = 'AutoGenerated'): {
  goCode: string;
  error?: string;
} {
  try {
    const parsed = JSON.parse(rawJson);
    const structs: string[] = [];

    function capitalize(str: string) {
      return str.charAt(0).toUpperCase() + str.slice(1);
    }

    function getGoType(val: any, keyName: string): string {
      if (val === null) return 'interface{}';
      if (typeof val === 'string') return 'string';
      if (typeof val === 'number') return Number.isInteger(val) ? 'int' : 'float64';
      if (typeof val === 'boolean') return 'bool';

      if (Array.isArray(val)) {
        if (val.length === 0) return '[]interface{}';
        const itemType = getGoType(val[0], `${keyName}Item`);
        return `[]${itemType}`;
      }

      if (typeof val === 'object') {
        const subName = capitalize(keyName);
        generateStruct(val, subName);
        return subName;
      }

      return 'interface{}';
    }

    function generateStruct(obj: Record<string, any>, name: string) {
      const lines = [`type ${name} struct {`];
      for (const [key, value] of Object.entries(obj)) {
        const fieldName = capitalize(key.replace(/[^a-zA-Z0-9]/g, ''));
        const typeStr = getGoType(value, key);
        lines.push(`\t${fieldName || 'Field'} ${typeStr} \`json:"${key}"\``);
      }
      lines.push('}');
      structs.push(lines.join('\n'));
    }

    if (typeof parsed === 'object' && parsed !== null && !Array.isArray(parsed)) {
      generateStruct(parsed, rootStructName);
    } else {
      return { goCode: '// Root is not an object. Wrap JSON in an object for Go structs.' };
    }

    return { goCode: structs.join('\n\n') };
  } catch (err: any) {
    return { goCode: '', error: `Go Struct Generator Error: ${err.message}` };
  }
}
